/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eu_smileyik_luaInMinecraftBukkitII_jniBridge_JNIBridge */

#ifndef _Included_org_eu_smileyik_luaInMinecraftBukkitII_jniBridge_JNIBridge
#define _Included_org_eu_smileyik_luaInMinecraftBukkitII_jniBridge_JNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eu_smileyik_luaInMinecraftBukkitII_jniBridge_JNIBridge
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_eu_smileyik_luaInMinecraftBukkitII_jniBridge_JNIBridge_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
